### ISSUE TITLE
User can stop sharing after files have been sent

### ISSUE THREAD

**Issue by n8fr8** [tladesignz/AdParticipesCumCepis#10]
When a user selects share mode, they can uncheck the box, "Stop sharing after files have been sent (uncheck to allow downloading individual files)". 

If checked, then the service only allows users to download all files at once, and as soon as the first download finishes the service stops.

**Comment by tladesignz** [comment]
Not implemented, yet, as the [`GCDWebServer`](https://github.com/swisspol/GCDWebServer) library doesn't support that feature.

Will need to fork and add there, hopefully getting accepted in upstream.

Does this really need to be in the MVP? Doesn't sound very MVP to me.

**Comment by tladesignz** [comment]
Aha. Maybe I can hack something together with this:

https://github.com/swisspol/GCDWebServer/blob/master/GCDWebServer/Core/GCDWebServer.h#L268-L289
