### ISSUE TITLE
allow user to choose one or more files to share

### ISSUE THREAD

**Issue by n8fr8** [tladesignz/AdParticipesCumCepis#2]

**Comment by tladesignz** [comment]
Users can share…

- …their photos and videos:

https://github.com/tladesignz/AdParticipesCumCepis/blob/main/AdParticipesCumCepis/Classes/Share/ShareViewController.swift#L139-L144

https://github.com/tladesignz/AdParticipesCumCepis/blob/main/AdParticipesCumCepis/Classes/Share/ShareViewController.swift#L365-L378

- …their documents:

https://github.com/tladesignz/AdParticipesCumCepis/blob/main/AdParticipesCumCepis/Classes/Share/ShareViewController.swift#L146-L151

https://github.com/tladesignz/AdParticipesCumCepis/blob/main/AdParticipesCumCepis/Classes/Share/ShareViewController.swift#L433-L450

- …and files they explicitly stored in the app via iTunes on their computer or via the `Files` app in iOS:

https://github.com/tladesignz/AdParticipesCumCepis/blob/main/AdParticipesCumCepis/Classes/Share/ShareViewController.swift#L132-L133

https://github.com/tladesignz/AdParticipesCumCepis/blob/main/Example/AdParticipesCumCepis/Info.plist#L25-L26

https://github.com/tladesignz/AdParticipesCumCepis/blob/main/Example/AdParticipesCumCepis/Info.plist#L33-L34
