### ISSUE TITLE
if multiple files, have option to share/download zip archive

### ISSUE THREAD

**Issue by n8fr8** [tladesignz/AdParticipesCumCepis#3]

**Comment by tladesignz** [comment]
Implemented here:

https://github.com/tladesignz/AdParticipesCumCepis/blob/main/AdParticipesCumCepis/Classes/Utils/WebServer.swift#L141-L174

https://github.com/tladesignz/AdParticipesCumCepis/blob/main/AdParticipesCumCepis/Classes/Utils/WebServer.swift#L286-L331
