### ISSUE TITLE
start onionservice with http server

### ISSUE THREAD

**Issue by n8fr8** [tladesignz/AdParticipesCumCepis#5]

**Comment by tladesignz** [comment]
Implemented here:

https://github.com/tladesignz/AdParticipesCumCepis/blob/main/AdParticipesCumCepis/Classes/Utils/WebServer.swift

https://github.com/tladesignz/AdParticipesCumCepis/blob/main/AdParticipesCumCepis/Classes/Utils/TorManager.swift#L80-L99
