### ISSUE TITLE
allow user to share HTTP onion url for their onionservice

### ISSUE THREAD

**Issue by n8fr8** [tladesignz/AdParticipesCumCepis#7]
- copy and paste
- sharesheet?
- QR code?

**Comment by tladesignz** [comment]
### Copy/paste:

https://github.com/tladesignz/AdParticipesCumCepis/blob/main/AdParticipesCumCepis/Classes/Share/ShareViewController.swift#L276-L284

### QR Code:
https://github.com/tladesignz/AdParticipesCumCepis/blob/main/AdParticipesCumCepis/Classes/Share/ShareViewController.swift#L286-L300

https://github.com/tladesignz/AdParticipesCumCepis/blob/main/AdParticipesCumCepis/Classes/Share/ShowQrViewController.swift

### Sharesheet

Nice idea! 

However, before I implement that, can we talk about a URL format which includes both the address and the key?

I suggest two options:

1. Use "password" piece of URL:

```
http://:somerandomkey@example.onion/
```

- Cons:
  - Looks strange to most users.
  - Unsure if messenger clients destroy that.

- Pro:
  - Actually exactly where it belongs.
  - Perfectly valid.
  - Doesn't end up in server logs.

2. Use a "key" query:
```
http://example.onion/?key=somerandomkey
```

- Cons:
  - Arbitrary, non-standard "key" value.
  - Might end up in server logs.

- Pros:
  - Looks more familiar to users.
  - Highly unlikely that it gets mangled by any client.

**Comment by tladesignz** [comment]
Let's discuss there: https://github.com/onionshare/onionshare-shared/issues/2

**Comment by tladesignz** [comment]
I replaced the clipboard and QR code buttons with a share sheet, which is way more iOS-sy. That supports copy-to-clipboard and QR code display just as well and doesn't take up so much screen estate.

So, all done here, but let's discuss the URL format over at onionshare-share further!
