### ISSUE TITLE
onionservice should support client authentication aka "private mode"

### ISSUE THREAD

**Issue by n8fr8** [tladesignz/AdParticipesCumCepis#8]
- if enable, key must be displayed for user to copy and share as they need to

**Comment by tladesignz** [comment]
Implemented here:

https://github.com/tladesignz/AdParticipesCumCepis/blob/main/AdParticipesCumCepis/Classes/Share/ShareViewController.swift#L79-L83

https://github.com/tladesignz/AdParticipesCumCepis/blob/main/AdParticipesCumCepis/Classes/Share/ShareViewController.swift#L176-L237
